services:
  czkawka-web:
    build: .
    container_name: czkawka-web
    ports:
      - "${PORT:-6198}:${PORT:-6198}"
    environment:
      - PORT=${PORT:-6198}
    volumes:
      - ./data:/data
      - ${SCAN_PATH:?error}:/mnt/files
    restart: unless-stopped
